#!/usr/bin/env tsx

import fs from 'fs';
import path from 'path';

// Read package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Generate version.ts content
const versionContent = `// This file is auto-generated by hack/generate-version.ts
export const VERSION = '${packageJson.version}';
`;

// Write version.ts
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionTsPath, versionContent);

console.log(`Generated version.ts with version ${packageJson.version}`);